<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="70" started-at="2019-02-10T15:06:00Z" finished-at="2019-02-10T15:06:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="70" started-at="2019-02-10T15:06:00Z" finished-at="2019-02-10T15:06:00Z">
      <class name="com.testngsetup.AllDropdownDataValidation">
        <test-method status="FAIL" signature="runDataVerificationTest()[pri:200, instance:com.testngsetup.AllDropdownDataValidation@464bee09]" name="runDataVerificationTest" duration-ms="24" started-at="2019-02-10T15:06:00Z" finished-at="2019-02-10T15:06:00Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.testngsetup.AllDropdownDataFromWebsite.getAllDropdownData(AllDropdownDataFromWebsite.java:13)
at com.testngsetup.AllDropdownDataValidation.runDataVerificationTest(AllDropdownDataValidation.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runDataVerificationTest -->
        <test-method status="PASS" signature="runDataValidationTest()[pri:300, instance:com.testngsetup.AllDropdownDataValidation@464bee09]" name="runDataValidationTest" duration-ms="2" started-at="2019-02-10T15:06:00Z" finished-at="2019-02-10T15:06:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runDataValidationTest -->
      </class> <!-- com.testngsetup.AllDropdownDataValidation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
